import type { Metadata, Viewport } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";

export const metadata: Metadata = {
  metadataBase: new URL("https://fellow.space"),
  title: "Fellow — find a meeting, find your people",
  description: "Find AA, NA, and other recovery meetings near you — 12-step fellowships and related peer-support programs, all in one place.",
  applicationName: "Fellow",
  appleWebApp: { capable: true, statusBarStyle: "default", title: "Fellow" },
  alternates: { canonical: "/" },
  verification: {
    google: "AZ7CKel0W969wLS0rlYvlEpXarmSczeJYWTcUmUPJ7Y",
    other: { "msvalidate.01": "7E6561D41455669D0245550B6A8F5444" }, // Bing
  },
  // Let search engines show large image previews and full-length snippets for richer results.
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 },
  },
  category: "health",
  openGraph: {
    title: "Fellow — find a meeting, find your people",
    description: "Find AA, NA, and other recovery meetings near you — 12-step and related peer-support programs, all in one place.",
    url: "/",
    siteName: "Fellow",
    type: "website",
    locale: "en_US",
    // og:image is generated by app/opengraph-image.tsx (a 1200×630 branded card).
  },
  twitter: {
    card: "summary_large_image",
    title: "Fellow — find a meeting, find your people",
    description: "Find AA, NA, and other recovery meetings near you.",
  },
};

export const viewport: Viewport = {
  themeColor: "#0f766e",
  colorScheme: "light dark",
};

// Structured data: tells search engines what Fellow is (Organization) and enables the
// sitelinks search box (WebSite + SearchAction → /?q=…). Keep in sync with the ?q= handling
// in page.tsx / Finder.tsx.
const JSONLD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://fellow.space/#org",
      name: "Fellow",
      url: "https://fellow.space",
      logo: "https://fellow.space/icon-512.png",
      description: "A free, independent, non-commercial finder for 12-step and related peer-support recovery meetings across the US.",
      areaServed: "US",
      nonprofitStatus: "Nonprofit",
      knowsAbout: [
        "Alcoholics Anonymous", "Narcotics Anonymous", "Al-Anon", "recovery meetings",
        "12-step programs", "addiction recovery", "peer support",
      ],
    },
    {
      "@type": "WebSite",
      "@id": "https://fellow.space/#website",
      url: "https://fellow.space",
      name: "Fellow",
      description: "Find AA, NA, and other recovery meetings near you.",
      inLanguage: "en-US",
      publisher: { "@id": "https://fellow.space/#org" },
      potentialAction: {
        "@type": "SearchAction",
        target: { "@type": "EntryPoint", urlTemplate: "https://fellow.space/?q={search_term_string}" },
        "query-input": "required name=search_term_string",
      },
    },
  ],
};

// Warm up the connection to the Typesense search host during idle page load so the first
// Search query doesn't pay the DNS + TLS handshake. React 19 hoists these <link>s to <head>.
const TS_HOST = process.env.NEXT_PUBLIC_TYPESENSE_HOST;
const TS_ORIGIN = TS_HOST && TS_HOST !== "localhost" ? `https://${TS_HOST}` : null;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {TS_ORIGIN && <link rel="preconnect" href={TS_ORIGIN} crossOrigin="anonymous" />}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(JSONLD) }} />
        <a href="#main-content" className="skip-link">Skip to content</a>
        {children}
        <ServiceWorkerRegister />
        <Analytics />
      </body>
    </html>
  );
}
