// Fellowship taxonomy for the indexer (mirror of src/lib/fellowships.ts).
// Keep in sync; used to add searchable full name + synonyms to each meeting doc.
export const FELLOWSHIPS = [
  ["AA","Alcoholics Anonymous",["alcohol","alcoholic","drinking","drink","sober","sobriety","booze","drunk"]],
  ["NA","Narcotics Anonymous",["drugs","narcotics","addict","addiction","using","clean"]],
  ["CA","Cocaine Anonymous",["cocaine","crack","coke"]],
  ["HA","Heroin Anonymous",["heroin","opioid","opiate","opioids","fentanyl","dope"]],
  ["MA","Marijuana Anonymous",["marijuana","cannabis","weed","pot","thc"]],
  ["CMA","Crystal Meth Anonymous",["crystal meth","methamphetamine","meth","tina"]],
  ["NicA","Nicotine Anonymous",["nicotine","smoking","smoke","vaping","vape","cigarettes","tobacco"]],
  ["PA","Pills Anonymous",["pills","prescription","benzos","painkillers","xanax"]],
  ["OA","Overeaters Anonymous",["overeating","overeater","food","compulsive eating","binge eating","binge","sugar"]],
  ["EDA","Eating Disorders Anonymous",["eating disorder","anorexia","bulimia","disordered eating","purging"]],
  ["FAIR","Food Addicts in Recovery Anonymous",["food addiction","food addict","food","sugar"]],
  ["FAA","Food Addicts Anonymous",["food addiction","food addict","food","sugar"]],
  ["SAA","Sex Addicts Anonymous",["sex addiction","sex addict","sex","porn","pornography","lust"]],
  ["SA","Sexaholics Anonymous",["sexaholic","sex","lust","porn"]],
  ["SLAA","Sex and Love Addicts Anonymous",["sex and love","love addiction","love addict","relationships","dating","romance"]],
  ["SCA","Sexual Compulsives Anonymous",["sexual compulsion","sexual compulsive","sex","compulsive sex"]],
  ["SRA","Sexual Recovery Anonymous",["sexual recovery","sex"]],
  ["SIA","Survivors of Incest Anonymous",["incest","abuse survivor","sexual abuse","childhood abuse","trauma"]],
  ["COSLAA","CoSex and Love Addicts Anonymous",["coslaa","affected by sex and love","partner sex addiction"]],
  ["DA","Debtors Anonymous",["debt","debtor","money","spending","overspending","finances","financial"]],
  ["UA","Underearners Anonymous",["underearning","underearner","income","earning","money"]],
  ["WA","Workaholics Anonymous",["workaholism","workaholic","work","overworking","burnout"]],
  ["CLA","Clutterers Anonymous",["clutter","clutterer","hoarding","hoarder","messy","disorganized","disorganization"]],
  ["EA","Emotions Anonymous",["emotions","emotional","anxiety","depression","mental health","feelings","stress"]],
  ["GA","Gamblers Anonymous",["gambling","gambler","betting","bet","casino","sports betting"]],
  ["CoDA","Co-Dependents Anonymous",["codependency","codependent","codependence","relationships","enabling"]],
  ["ACA","Adult Children of Alcoholics & Dysfunctional Families",["adult children","acoa","aca","dysfunctional family","childhood trauma"]],
  ["Al-Anon","Al-Anon Family Groups",["families of alcoholics","loved ones","family","spouse","partner drinking","affected by drinking"]],
  ["Alateen","Alateen",["teens","teenager","teen","family","youth"]],
  ["Nar-Anon","Nar-Anon Family Groups",["families of addicts","family","loved one using","affected by drugs"]],
  ["Gam-Anon","Gam-Anon",["families of gamblers","family","affected by gambling"]],
  ["Co-Anon","Co-Anon",["families of addicts","family","cocaine","affected by cocaine"]],
  ["FA","Families Anonymous",["families","family","loved ones","substance abuse"]],
];
const BY = Object.fromEntries(FELLOWSHIPS.map(([c, name, kw]) => [c, { name, kw }]));
export const fellowshipName = (c) => BY[c]?.name || c;
export const fellowshipTerms = (c) => (BY[c] ? [BY[c].name, ...BY[c].kw].join(" ") : "");
